# Generated by Django 5.2.6 on 2025-09-15 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('place_type', models.CharField(max_length=100, verbose_name='Тип місця')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Локація')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
                'ordering': ['-created_at'],
            },
        ),
    ]
