# Generated by Django 5.2.6 on 2025-09-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва кафедри')),
                ('head_of_department', models.CharField(max_length=150, verbose_name='Завідувач кафедрою')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Головна сторінка', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис факультету')),
                ('contact_info', models.TextField(verbose_name='Контактна інформація')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=50, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Повний опис')),
                ('coordinator_name', models.CharField(max_length=150, verbose_name="Ім'я координатора набору")),
                ('coordinator_contact', models.CharField(max_length=200, verbose_name='Контакт координатора набору')),
                ('disciplines', models.TextField(help_text='Перерахуйте дисципліни через кому', verbose_name='Список дисциплін')),
                ('graduating_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='faculty.department', verbose_name='Випускаюча кафедра')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я викладача")),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('degree', models.CharField(max_length=100, verbose_name='Науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='faculty.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
    ]
